// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Notifon.Server.Database;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace Notifon.Server.Database.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20211009085937_MultiEndpoints")]
    partial class MultiEndpoints
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.10")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("Notifon.Server.Database.Models.EndpointModel", b =>
                {
                    b.Property<string>("Endpoint")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<int>("EndpointType")
                        .HasColumnType("integer");

                    b.Property<string>("Parameters")
                        .HasColumnType("text");

                    b.HasKey("Endpoint", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Endpoints");
                });

            modelBuilder.Entity("Notifon.Server.Database.Models.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("SecretKey")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Notifon.Server.Database.Models.EndpointModel", b =>
                {
                    b.HasOne("Notifon.Server.Database.Models.User", "User")
                        .WithMany("Endpoints")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Notifon.Server.Database.Models.User", b =>
                {
                    b.Navigation("Endpoints");
                });
#pragma warning restore 612, 618
        }
    }
}
