all: PubkeyRecovery.code RecoverableMultisigWallet.code

PubkeyRecovery.code: PubkeyRecovery.sol
	ft contract build PubkeyRecovery.sol -f


RecoverableMultisigWallet.code: RecoverableMultisigWallet.sol
	ft contract build RecoverableMultisigWallet.sol -f
