{
 "title": "Notifon",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ConsumerType", "query": { "query": "label_values(consumer_type)" } },
   { "name": "MessageType", "query": { "query": "label_values(message_type)" } },
   {
    "name": "PublishMessageTypes",
    "query": {
     "query": "label_values(mt_publish_total,message_type)"
    }
   },
   {
    "name": "SendMessageTypes",
    "query": {
     "query": "label_values(mt_send_total,message_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m])",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    { "expr": "process_working_set_bytes", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 8, "w": 5, "x": 10, "y": 0 } },
  { "title": "Consume", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Consume Duration",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mt_consume_duration_seconds_bucket[5m])) by (message_type,le))  ",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Delivery Duration",
   "type": "graph",
   "gridPos": { "h": 11, "w": 11, "x": 11, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(mt_delivery_duration_seconds_bucket[5m])) by (message_type,le))",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Publish Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mt_publish_total{message_type=~\"[[PublishMessageTypes]]\"}[5m])",
     "legendFormat": "{{message_type}}"
    }
   ]
  },
  {
   "title": "Receive Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 8, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "rate(mt_receive_total[5m])", "legendFormat": "{{endpoint_address}}" }
   ]
  },
  {
   "title": "Send Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 7, "x": 15, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(mt_send_total{message_type=~\"[[SendMessageTypes]]\"}[5m])",
     "legendFormat": "{{message_type}}"
    }
   ]
  }
 ]
}